### ISSUE TITLE
Remove duplicate header

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries-site#7]
The name of the registry is duplicated in the HTML template:

https://github.com/ISDCF/registries-site/blob/7d57c349907f0f551e7de6ec889c6b57a1f904d7/src/main/templates/facilities.hbs#L41

See discussion at:

https://github.com/ISDCF/registries-site/pull/6#pullrequestreview-455119723

**Comment by SteveLLamb** [comment]
This is now fixed in #6  - swapped out "fixed-top" to "sticky-top" in navbar. This allows for the fixed top in browsers that support (all current versions of IE, Chrome, Safari, Firefox, web and mobile), and renders as static top in those that don't support. Print out work much better as well, and no further overlaps of content.
